// angular-meal-planner/angular-recipes/src/app/components/recipe-card/recipe-card.component.ts
import { Component, Input, Output, EventEmitter, OnInit, HostListener, ElementRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { AuthService } from '../../services/auth.service';
import { UserRecipeService } from '../../services/user-recipe.service';
import { stripHtml } from '../../utils/html-utils';
import { environment } from '../../../environments/environment';

@Component({
    selector: 'app-recipe-card',
    standalone: true,
    imports: [CommonModule, FormsModule],
    templateUrl: './recipe-card.component.html',
    styleUrls: ['./recipe-card.component.scss']
})
export class RecipeCardComponent implements OnInit {
    @Input() recipe: any;
    @Input() featured: boolean = false;
    @Input() rating: number = 0;
    @Input() user: any = null;
    @Input() favorites: any[] = [];
    @Input() sharedByName: string | null = null;

    @Output() open = new EventEmitter<any>();
    @Output() deleted = new EventEmitter<string>();

    menuOpen = false;
    deleteDialogOpen = false;
    ratingDialogOpen = false;
    commentDialogOpen = false;
    sharePromptOpen = false;
    shareLinkDialogOpen = false;
    copySuccess = false;

    userRating = 0;
    newComment = '';
    myRecipeId: string | null = null;
    isMyRecipe = false;
    shareLoading = false;
    shareSuccess = false;
    isFavorite = false;

    private baseUrl = environment.jsonServerUrl;

    constructor(
        private router: Router,
        private http: HttpClient,
        private authService: AuthService,
        private userRecipeService: UserRecipeService,
        private elementRef: ElementRef
    ) { }

    ngOnInit() {
        // Check if recipe is a custom recipe (from My Recipe Book)
        this.isMyRecipe = this.recipe.isMine === true;

        // Subscribe to user changes
        this.authService.user$.subscribe(user => {
            this.user = user;
            if (user) {
                this.checkIfInBook();
                this.loadUserRating();
            }
        });

        // Subscribe to favorites changes
        this.userRecipeService.favorites$.subscribe(favorites => {
            this.favorites = favorites || [];
            this.updateFavoriteStatus();
        });

        // Initial check
        if (this.user) {
            this.checkIfInBook();
            this.loadUserRating();
        }
        this.updateFavoriteStatus();
    }

    @HostListener('document:click', ['$event'])
    clickout(event: any) {
        if (!this.elementRef.nativeElement.contains(event.target)) {
            this.menuOpen = false;
        }
    }

    updateFavoriteStatus() {
        this.isFavorite = this.favorites?.some(f => f.recipeId === this.recipe.id) || false;
    }

    async checkIfInBook() {
        if (!this.user || !this.recipe.id || this.isMyRecipe) return;

        try {
            const response: any = await this.http.get(
                `${this.baseUrl}/myRecipes?userId=${this.user.id}&sourceRecipeId=${this.recipe.id}`
            ).toPromise();

            if (response && response.length > 0) {
                this.myRecipeId = response[0].id;
            }
        } catch (err) {
            console.warn('Failed to check recipe book:', err);
        }
    }

    async loadUserRating() {
        if (!this.user || !this.recipe.id) return;

        try {
            const response: any = await this.http.get(
                `${this.baseUrl}/ratings?recipeId=${this.recipe.id}&userId=${this.user.id}`
            ).toPromise();

            if (response && response.length > 0) {
                this.userRating = response[0].stars;
            }
        } catch (err) {
            console.warn('Failed to load user rating:', err);
        }
    }

    handleClick() {
        if (this.open.observers.length > 0) {
            this.open.emit(this.recipe);
            return;
        }

        if (!this.user) {
            alert('Login to view details');
            return;
        }

        if (this.isMyRecipe) {
            this.router.navigate(['/my-recipes', this.recipe.id]);
        } else {
            this.router.navigate(['/recipe', this.recipe.id]);
        }
    }

    async toggleFavorite(event: Event) {
        event.stopPropagation();

        if (!this.user) {
            alert('Login to add favorites');
            return;
        }

        const existingFavorite = this.favorites.find(f => f.recipeId === this.recipe.id);

        if (existingFavorite) {
            // Optimistically update UI
            this.isFavorite = false;
            await this.userRecipeService.removeFavorite(existingFavorite.id);
        } else {
            // Optimistically update UI
            this.isFavorite = true;
            await this.userRecipeService.addFavorite(this.recipe);
        }
    }

    toggleMenu(event: Event) {
        event.stopPropagation();
        this.menuOpen = !this.menuOpen;
    }

    async addToBook(event: Event) {
        event.stopPropagation();
        this.menuOpen = false;

        if (!this.user) {
            alert('Login to share recipes');
            return;
        }

        try {
            // Ensure ingredients and instructions are in string format
            let ingredients = this.recipe.ingredients || '';
            let instructions = this.recipe.instructions || '';

            // If they're arrays, convert to numbered string format
            if (Array.isArray(this.recipe.ingredients)) {
                ingredients = this.recipe.ingredients
                    .filter((item: any) => item)
                    .map((item: any, idx: number) => `${idx + 1}. ${item}`)
                    .join('\n');
            }

            if (Array.isArray(this.recipe.instructions)) {
                instructions = this.recipe.instructions
                    .filter((item: any) => item)
                    .map((item: any, idx: number) => `${idx + 1}. ${item}`)
                    .join('\n');
            }

            const payload = {
                userId: this.user.id,
                sourceRecipeId: this.recipe.id,
                title: this.recipe.title,
                image: this.recipe.image,
                summary: this.recipe.summary || '',
                servings: this.recipe.servings || null,
                readyInMinutes: this.recipe.readyInMinutes || null,
                dishTypes: this.recipe.dishTypes || [],
                diets: this.recipe.diets || [],
                ingredients,
                instructions,
            };

            const saved: any = await this.http.post(`${this.baseUrl}/myRecipes`, payload).toPromise();
            this.myRecipeId = saved.id;
        } catch (err) {
            console.error('Add to book failed:', err);
        }
    }

    editInBook(event: Event) {
        event.stopPropagation();
        this.menuOpen = false;
        this.router.navigate(['/my-recipes', this.myRecipeId, 'edit']);
    }

    editRecipe(event: Event) {
        event.stopPropagation();
        this.menuOpen = false;
        this.router.navigate(['/my-recipes', this.recipe.id, 'edit']);
    }

    deleteRecipe(event: Event) {
        event.stopPropagation();
        this.menuOpen = false;
        this.deleteDialogOpen = true;
    }

    async handleDeleteConfirm() {
        try {
            await this.http.delete(`${this.baseUrl}/myRecipes/${this.recipe.id}`).toPromise();
            this.deleteDialogOpen = false;
            this.deleted.emit(this.recipe.id);
        } catch (err) {
            console.error('Delete failed:', err);
            alert('Failed to delete recipe');
            this.deleteDialogOpen = false;
        }
    }

    handleDeleteCancel() {
        this.deleteDialogOpen = false;
    }

    openRatingDialog(event: Event) {
        event.stopPropagation();
        this.menuOpen = false;
        this.ratingDialogOpen = true;
    }

    setUserRating(stars: number) {
        this.userRating = stars;
    }

    async handleRatingSubmit() {
        if (this.userRating === 0 || !this.user) return;

        try {
            // Check if user already rated
            const existing: any = await this.http.get(
                `${this.baseUrl}/ratings?recipeId=${this.recipe.id}&userId=${this.user.id}`
            ).toPromise();

            if (existing && existing.length > 0) {
                // Update existing rating
                await this.http.patch(
                    `${this.baseUrl}/ratings/${existing[0].id}`,
                    { stars: this.userRating }
                ).toPromise();
            } else {
                // Create new rating
                await this.http.post(`${this.baseUrl}/ratings`, {
                    recipeId: this.recipe.id,
                    userId: this.user.id,
                    stars: this.userRating,
                    createdAt: new Date().toISOString()
                }).toPromise();
            }

            this.ratingDialogOpen = false;
        } catch (err) {
            console.error('Rating submission failed:', err);
        }
    }

    openCommentDialog(event: Event) {
        event.stopPropagation();
        this.menuOpen = false;
        this.commentDialogOpen = true;
    }

    async handleCommentSubmit() {
        if (!this.newComment.trim() || !this.user) return;

        try {
            await this.http.post(`${this.baseUrl}/comments`, {
                recipeId: this.recipe.id,
                userId: this.user.id,
                userName: this.user.name || this.user.email,
                comment: this.newComment,
                createdAt: new Date().toISOString()
            }).toPromise();

            this.newComment = '';
            this.commentDialogOpen = false;
        } catch (err) {
            console.error('Comment submission failed:', err);
        }
    }

    async handleShareYes() {
        try {
            this.shareLoading = true;

            const sharedRecipe = {
                userId: this.user.id,
                userName: this.user.name || this.user.email,
                recipeId: this.recipe.id,
                recipeTitle: this.recipe.title,
                recipeImage: this.recipe.image,
                recipeSummary: this.recipe.summary || 'Delicious recipe shared by ' + (this.user.name || this.user.email),
                sharedAt: new Date().toISOString()
            };

            await this.http.post(`${this.baseUrl}/sharedRecipes`, sharedRecipe).toPromise();

            this.shareSuccess = true;

            setTimeout(() => {
                this.sharePromptOpen = false;
                this.shareSuccess = false;
            }, 1500);
        } catch (err) {
            console.error('Failed to share recipe:', err);
            this.sharePromptOpen = false;
        } finally {
            this.shareLoading = false;
        }
    }

    handleShareNo() {
        this.sharePromptOpen = false;
    }

    openShareLinkDialog(event: Event) {
        event.stopPropagation();
        this.menuOpen = false;
        this.shareLinkDialogOpen = true;
        this.copySuccess = false;
    }

    getShareableLink(): string {
        const baseUrl = window.location.origin;
        if (this.isMyRecipe) {
            return `${baseUrl}/my-recipes/${this.recipe.id}`;
        }
        return `${baseUrl}/shared/${this.recipe.id}`;
    }

    async copyShareLink() {
        try {
            const link = this.getShareableLink();
            await navigator.clipboard.writeText(link);
            this.copySuccess = true;
        } catch (err) {
            console.error('Failed to copy link:', err);
            // Fallback for older browsers
            const link = this.getShareableLink();
            const textarea = document.createElement('textarea');
            textarea.value = link;
            document.body.appendChild(textarea);
            textarea.select();
            document.execCommand('copy');
            document.body.removeChild(textarea);
            this.copySuccess = true;
        }

        // Reset after 2 seconds
        setTimeout(() => {
            this.copySuccess = false;
        }, 2000);
    }

    handleCopyClick(event: Event) {
        this.copyShareLink();
        // Blur the button to ensure state updates are visible
        const target = event.target as HTMLElement;
        target?.blur();
    }

    getStrippedSummary(): string {
        return stripHtml(this.recipe.summary || '');
    }
}

<div class="recipe-card" (click)="handleClick()">
    <!-- Featured Badge -->
    <div class="featured-badge" *ngIf="featured">⭐ Featured</div>

    <!-- Image Container with Actions Overlay -->
    <div class="image-container">
        <img [src]="recipe.image" [alt]="recipe.title" class="recipe-image" />

        <div class="actions-overlay">
            <!-- Favorite Button -->
            <button class="action-btn favorite-btn" (click)="toggleFavorite($event)" *ngIf="user && !sharedByName"
                aria-label="Toggle favorite" [title]="isFavorite ? 'Remove from favorites' : 'Add to favorites'">

                <!-- Outline Heart (not favorite) -->
                <svg *ngIf="!isFavorite" xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24">
                    <path d="M0 0h24v24H0z" fill="none" />
                    <path
                        d="M16.5 3c-1.74 0-3.41.81-4.5 2.09C10.91 3.81 9.24 3 7.5 3 4.42 3 2 5.42 2 8.5c0 3.78 3.4 6.86 8.55 11.54L12 21.35l1.45-1.32C18.6 15.36 22 12.28 22 8.5 22 5.42 19.58 3 16.5 3zm-4.4 15.55l-.1.1-.1-.1C7.14 14.24 4 11.39 4 8.5 4 6.5 5.5 5 7.5 5c1.54 0 3.04.99 3.57 2.36h1.87C13.46 5.99 14.96 5 16.5 5c2 0 3.5 1.5 3.5 3.5 0 2.89-3.14 5.74-7.9 10.05z" />
                </svg>
                <!-- Filled Heart (is favorite) -->
                <svg *ngIf="isFavorite" xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24">
                    <path d="M0 0h24v24H0z" fill="none" />
                    <path
                        d="M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41.81 4.5 2.09C13.09 3.81 14.76 3 16.5 3 19.58 3 22 5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54L12 21.35z" />
                </svg>
            </button>

            <!-- Menu Button -->
            <button class="action-btn menu-btn" (click)="toggleMenu($event)" *ngIf="user" aria-label="Open recipe menu"
                title="Open recipe menu">
                <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24">
                    <path d="M0 0h24v24H0z" fill="none" />
                    <path
                        d="M12 8c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2zm0 2c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm0 6c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2z" />
                </svg>
            </button>
        </div>

        <!-- Action Menu Dropdown -->
        <div class="action-menu" *ngIf="menuOpen" (click)="$event.stopPropagation()">
            <div class="menu-header" *ngIf="sharedByName">
                <svg xmlns="http://www.w3.org/2000/svg" height="16" viewBox="0 0 24 24" width="16" fill="currentColor">
                    <path d="M0 0h24v24H0z" fill="none" />
                    <path
                        d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z" />
                </svg>
                <span class="shared-by-text">Shared by <strong>{{ sharedByName }}</strong></span>
            </div>
            <button class="menu-item" *ngIf="!myRecipeId && !isMyRecipe" (click)="addToBook($event)">
                <svg xmlns="http://www.w3.org/2000/svg" height="20" viewBox="0 0 24 24" width="20">
                    <path d="M0 0h24v24H0z" fill="none" />
                    <path d="M19 13h-6v6h-2v-6H5v-2h6V5h2v6h6v2z" />
                </svg>
                Add to Recipe Book
            </button>
            <button class="menu-item" *ngIf="myRecipeId && !isMyRecipe" (click)="editInBook($event)">
                <svg xmlns="http://www.w3.org/2000/svg" height="20" viewBox="0 0 24 24" width="20">
                    <path d="M0 0h24v24H0z" fill="none" />
                    <path
                        d="M3 17.25V21h3.75L17.81 9.94l-3.75-3.75L3 17.25zM20.71 7.04c.39-.39.39-1.02 0-1.41l-2.34-2.34c-.39-.39-1.02-.39-1.41 0l-1.83 1.83 3.75 3.75 1.83-1.83z" />
                </svg>
                Edit in Book
            </button>
            <button class="menu-item" *ngIf="isMyRecipe" (click)="editRecipe($event)">
                <svg xmlns="http://www.w3.org/2000/svg" height="20" viewBox="0 0 24 24" width="20">
                    <path d="M0 0h24v24H0z" fill="none" />
                    <path
                        d="M3 17.25V21h3.75L17.81 9.94l-3.75-3.75L3 17.25zM20.71 7.04c.39-.39.39-1.02 0-1.41l-2.34-2.34c-.39-.39-1.02-.39-1.41 0l-1.83 1.83 3.75 3.75 1.83-1.83z" />
                </svg>
                Edit
            </button>
            <button class="menu-item delete-item" *ngIf="isMyRecipe" (click)="deleteRecipe($event)">
                <svg xmlns="http://www.w3.org/2000/svg" height="20" viewBox="0 0 24 24" width="20">
                    <path d="M0 0h24v24H0z" fill="none" />
                    <path d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM19 4h-3.5l-1-1h-5l-1 1H5v2h14V4z" />
                </svg>
                Delete
            </button>
            <button class="menu-item" (click)="openRatingDialog($event)">
                <svg xmlns="http://www.w3.org/2000/svg" height="20" viewBox="0 0 24 24" width="20">
                    <path d="M0 0h24v24H0z" fill="none" />
                    <path
                        d="M12 17.27L18.18 21l-1.64-7.03L22 9.24l-7.19-.61L12 2 9.19 8.63 2 9.24l5.46 4.73L5.82 21z" />
                </svg>
                Rate Recipe
            </button>
            <button class="menu-item" (click)="openCommentDialog($event)">
                <svg xmlns="http://www.w3.org/2000/svg" height="20" viewBox="0 0 24 24" width="20">
                    <path d="M0 0h24v24H0z" fill="none" />
                    <path
                        d="M21.99 4c0-1.1-.89-2-1.99-2H4c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h14l4 4-.01-18zM18 14H6v-2h12v2zm0-3H6V9h12v2zm0-3H6V6h12v2z" />
                </svg>
                Add Comment
            </button>
            <button class="menu-item" (click)="openShareLinkDialog($event)">
                <svg xmlns="http://www.w3.org/2000/svg" height="20" viewBox="0 0 24 24" width="20">
                    <path d="M0 0h24v24H0z" fill="none" />
                    <path
                        d="M18 16.08c-.76 0-1.44.3-1.96.77L8.91 12.7c.05-.23.09-.46.09-.7s-.04-.47-.09-.7l7.05-4.11c.54.5 1.25.81 2.04.81 1.66 0 3-1.34 3-3s-1.34-3-3-3-3 1.34-3 3c0 .24.04.47.09.7L8.04 9.81C7.5 9.31 6.79 9 6 9c-1.66 0-3 1.34-3 3s1.34 3 3 3c.79 0 1.5-.31 2.04-.81l7.12 4.16c-.05.21-.08.43-.08.65 0 1.61 1.31 2.92 2.92 2.92 1.61 0 2.92-1.31 2.92-2.92s-1.31-2.92-2.92-2.92z" />
                </svg>
                Share Recipe
            </button>
        </div>
    </div>

    <!-- Card Content -->
    <div class="recipe-content">
        <h3 class="recipe-title">{{ recipe.title }}</h3>
        <p class="recipe-summary">{{ getStrippedSummary() }}</p>

        <!-- Rating Display -->
        <div class="rating-display" *ngIf="rating && rating > 0">
            <svg xmlns="http://www.w3.org/2000/svg" height="16" viewBox="0 0 24 24" width="16">
                <path d="M0 0h24v24H0z" fill="none" />
                <path d="M12 17.27L18.18 21l-1.64-7.03L22 9.24l-7.19-.61L12 2 9.19 8.63 2 9.24l5.46 4.73L5.82 21z" />
            </svg>
            <span class="rating-value">{{ rating.toFixed(1) }}</span>
        </div>

        <!-- Metadata -->
        <div class="recipe-meta">
            <span *ngIf="recipe.readyInMinutes" class="meta-item">
                ⏱️ {{ recipe.readyInMinutes }} min
            </span>
            <span *ngIf="recipe.servings" class="meta-item">
                👥 {{ recipe.servings }} servings
            </span>
        </div>
    </div>
</div>

<!-- Delete Confirmation Dialog -->
<div class="dialog-overlay" *ngIf="deleteDialogOpen" (click)="handleDeleteCancel()">
    <div class="dialog" (click)="$event.stopPropagation()">
        <h2 class="dialog-title">Delete Recipe?</h2>
        <p class="dialog-content">Are you sure you want to delete "{{ recipe.title }}"? This action cannot be undone.
        </p>
        <div class="dialog-actions">
            <button class="dialog-btn" (click)="handleDeleteCancel()">Cancel</button>
            <button class="dialog-btn primary" (click)="handleDeleteConfirm()">Delete</button>
        </div>
    </div>
</div>

<!-- Rating Dialog -->
<div class="dialog-overlay" *ngIf="ratingDialogOpen" (click)="ratingDialogOpen = false">
    <div class="dialog" (click)="$event.stopPropagation()">
        <h2 class="dialog-title">Rate Recipe</h2>
        <div class="dialog-content">
            <h3 class="recipe-name">{{ recipe.title }}</h3>
            <div class="star-rating">
                <button *ngFor="let star of [1,2,3,4,5]" class="star-btn" (click)="setUserRating(star)"
                    [class.filled]="star <= userRating"
                    [attr.aria-label]="'Rate ' + star + ' star' + (star !== 1 ? 's' : '')"
                    [attr.title]="'Rate ' + star + ' star' + (star !== 1 ? 's' : '')">">
                    <svg xmlns="http://www.w3.org/2000/svg" height="40" viewBox="0 0 24 24" width="40">
                        <path d="M0 0h24v24H0z" fill="none" />
                        <path
                            d="M12 17.27L18.18 21l-1.64-7.03L22 9.24l-7.19-.61L12 2 9.19 8.63 2 9.24l5.46 4.73L5.82 21z" />
                    </svg>
                </button>
            </div>
            <p class="rating-text">
                {{ userRating > 0 ? 'You rated this recipe ' + userRating + ' star' + (userRating !== 1 ? 's' : '') :
                'Select a rating' }}
            </p>
        </div>
        <div class="dialog-actions">
            <button class="dialog-btn" (click)="ratingDialogOpen = false">Cancel</button>
            <button class="dialog-btn primary" (click)="handleRatingSubmit()" [disabled]="userRating === 0">
                Submit Rating
            </button>
        </div>
    </div>
</div>

<!-- Comment Dialog -->
<div class="dialog-overlay" *ngIf="commentDialogOpen" (click)="commentDialogOpen = false">
    <div class="dialog" (click)="$event.stopPropagation()">
        <h2 class="dialog-title">Add Comment</h2>
        <div class="dialog-content">
            <h3 class="recipe-name">{{ recipe.title }}</h3>
            <textarea class="comment-input" [(ngModel)]="newComment"
                placeholder="Share your thoughts about this recipe..." rows="4"></textarea>
        </div>
        <div class="dialog-actions">
            <button class="dialog-btn" (click)="commentDialogOpen = false">Cancel</button>
            <button class="dialog-btn primary" (click)="handleCommentSubmit()" [disabled]="!newComment.trim()">
                Add Comment
            </button>
        </div>
    </div>
</div>

<!-- Share Prompt Dialog -->
<div class="dialog-overlay" *ngIf="sharePromptOpen" (click)="shareLoading ? null : handleShareNo()">
    <div class="dialog" (click)="$event.stopPropagation()">
        <h2 class="dialog-title">{{ shareSuccess ? 'Recipe Shared!' : 'Would you share this recipe?' }}</h2>
        <p class="dialog-content">
            {{ shareSuccess
            ? '"' + recipe.title + '" has been shared with the community successfully 'You\'ve added "' + recipe.title + '" to your favorites! Would you like to share this recipe with others?'
            }}
        </p>
        <div class="dialog-actions" *ngIf="!shareSuccess">
            <button class="dialog-btn" (click)="handleShareNo()" [disabled]="shareLoading">No, Thanks</button>
            <button class="dialog-btn primary" (click)="handleShareYes()" [disabled]="shareLoading">
                {{ shareLoading ? 'Sharing...' : 'Yes, Share' }}
            </button>
        </div>
    </div>
</div>

<!-- Share Link Dialog -->
<div class="dialog-overlay" *ngIf="shareLinkDialogOpen" (click)="shareLinkDialogOpen = false">
    <div class="dialog" (click)="$event.stopPropagation()">
        <button class="dialog-close-btn" (click)="shareLinkDialogOpen = false" aria-label="Close dialog">
            <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24">
                <path d="M0 0h24v24H0z" fill="none" />
                <path
                    d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z" />
            </svg>
        </button>
        <h2 class="dialog-title">Share Recipe</h2>
        <div class="dialog-content">
            <h3 class="recipe-name">{{ recipe.title }}</h3>
            <p class="share-link-text">Share this recipe link with others:</p>
            <div class="share-link-container">
                <input type="text" class="share-link-input" [value]="getShareableLink()" readonly
                    aria-label="Shareable recipe link" title="Click to select link" (click)="$event.target.select()" />
                <button class="dialog-btn primary copy-link-btn" (click)="handleCopyClick($event)"
                    aria-label="Copy link to clipboard">
                    {{ copySuccess ? '✓ Copied!' : 'Copy Link' }}
                </button>
            </div>
        </div>
    </div>
</div>

// react-meal-planner/react-recipes/src/components/RecipeCard.js
import React, { useState, useEffect } from 'react';
import {
    Card, CardMedia, CardContent, Typography, IconButton, Box, Tooltip, Menu, MenuItem,
    Dialog, DialogTitle, DialogContent, DialogContentText, DialogActions, Button,
    TextField, Rating
} from '@mui/material';
import FavoriteIcon from '@mui/icons-material/Favorite';
import StarIcon from '@mui/icons-material/Star';
import MoreVertIcon from '@mui/icons-material/MoreVert';
import RateReviewIcon from '@mui/icons-material/RateReview';
import CommentIcon from '@mui/icons-material/Comment';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { addMyRecipe, getMyRecipes, deleteMyRecipe, getUserRating, upsertRating, addComment } from '../services/jsonServerAPI';
import { stripHtml } from '../utils/htmlUtils';
import axios from 'axios';

function RecipeCard({ recipe, featured, rating, onOpen, onDeleted }) {
    const navigate = useNavigate();
    const { user, favorites, addFavorite, removeFavorite } = useAuth();
    const [menuAnchor, setMenuAnchor] = useState(null);
    const [myRecipeId, setMyRecipeId] = useState(null);
    const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);
    const [ratingDialogOpen, setRatingDialogOpen] = useState(false);
    const [commentDialogOpen, setCommentDialogOpen] = useState(false);
    const [sharePromptOpen, setSharePromptOpen] = useState(false);
    const [justAddedRecipe, setJustAddedRecipe] = useState(null);
    const [shareLoading, setShareLoading] = useState(false);
    const [shareSuccess, setShareSuccess] = useState(false);
    const [userRating, setUserRating] = useState(0);
    const [newComment, setNewComment] = useState('');

    // If recipe has isMine property, it's already from My Recipe Book
    const isMyRecipe = recipe.isMine === true;

    // Check if this recipe is already in user's book
    useEffect(() => {
        let mounted = true;
        const checkInBook = async () => {
            if (!user || !recipe.id || isMyRecipe) return;
            try {
                const myRecipes = await getMyRecipes(user.id);
                const existing = myRecipes.find(r => r.sourceRecipeId === recipe.id);
                if (mounted && existing) {
                    setMyRecipeId(existing.id);
                }
            } catch (err) {
                console.warn('Failed to check recipe book:', err);
            }
        };
        checkInBook();
        return () => { mounted = false };
    }, [user, recipe.id, isMyRecipe]);

    // Load user's existing rating
    useEffect(() => {
        let mounted = true;
        const loadUserRating = async () => {
            if (!user || !recipe.id) return;
            try {
                const rating = await getUserRating(recipe.id, user.id);
                if (mounted && rating) {
                    setUserRating(rating.stars);
                }
            } catch (err) {
                console.warn('Failed to load user rating:', err);
            }
        };
        loadUserRating();
        return () => { mounted = false };
    }, [user, recipe.id]);

    const defaultOpen = () => {
        if (user) {
            // If it's a custom recipe (from My Recipe Book), navigate to custom recipe detail
            if (isMyRecipe) {
                navigate(`/my-recipes/${recipe.id}`);
            } else {
                navigate(`/recipe/${recipe.id}`);
            }
        } else {
            navigate('/login', { state: { from: window.location.pathname } });
        }
    };

    const handleClick = () => {
        if (onOpen) return onOpen(recipe);
        return defaultOpen();
    };

    const fav = favorites?.find((f) => f.recipeId === recipe.id);

    const handleToggleFavorite = async (e) => {
        e.stopPropagation();
        if (!user) {
            // optionally navigate to login
            navigate('/login', { state: { from: window.location.pathname } });
            return;
        }

        if (fav) {
            await removeFavorite(fav.id);
        } else {
            await addFavorite(recipe);
            // Show share prompt after adding to favorites
            setJustAddedRecipe(recipe);
            setSharePromptOpen(true);
        }
    };

    const handleSharePromptYes = async () => {
        try {
            setShareLoading(true);

            // Create shared recipe entry
            const sharedRecipe = {
                userId: user.id,
                userName: user.name || user.email,
                recipeId: justAddedRecipe.id,
                recipeTitle: justAddedRecipe.title,
                recipeImage: justAddedRecipe.image,
                recipeSummary: justAddedRecipe.summary || 'Delicious recipe shared by ' + (user.name || user.email),
                sharedAt: new Date().toISOString()
            };

            await axios.post('http://localhost:5001/sharedRecipes', sharedRecipe);

            // Show success state
            setShareSuccess(true);

            // Close dialog after a brief moment
            setTimeout(() => {
                setSharePromptOpen(false);
                setJustAddedRecipe(null);
                setShareSuccess(false);
            }, 1500);
        } catch (err) {
            console.error('Failed to share recipe:', err);
            setSharePromptOpen(false);
            setJustAddedRecipe(null);
        } finally {
            setShareLoading(false);
        }
    };

    const handleSharePromptNo = () => {
        setSharePromptOpen(false);
        setJustAddedRecipe(null);
    };

    const handleMenuOpen = (e) => {
        e.stopPropagation();
        setMenuAnchor(e.currentTarget);
    };

    const handleMenuClose = (e) => {
        e?.stopPropagation?.();
        setMenuAnchor(null);
    };

    const handleAddToBook = async (e) => {
        e.stopPropagation();
        if (!user) {
            navigate('/login', { state: { from: window.location.pathname } });
            return;
        }
        try {
            // Ensure ingredients and instructions are in string format
            let ingredients = recipe.ingredients || '';
            let instructions = recipe.instructions || '';

            // If they're arrays, convert to numbered string format
            if (Array.isArray(recipe.ingredients)) {
                ingredients = recipe.ingredients
                    .filter(Boolean)
                    .map((item, idx) => `${idx + 1}. ${item}`)
                    .join('\n');
            }

            if (Array.isArray(recipe.instructions)) {
                instructions = recipe.instructions
                    .filter(Boolean)
                    .map((item, idx) => `${idx + 1}. ${item}`)
                    .join('\n');
            }

            const payload = {
                userId: user.id,
                sourceRecipeId: recipe.id,
                title: recipe.title,
                image: recipe.image,
                summary: recipe.summary || '',
                servings: recipe.servings || null,
                readyInMinutes: recipe.readyInMinutes || null,
                dishTypes: recipe.dishTypes || [],
                diets: recipe.diets || [],
                ingredients,
                instructions,
            };
            const saved = await addMyRecipe(payload);
            setMyRecipeId(saved.id);
        } catch (err) {
            console.error('Add to book failed:', err);
        } finally {
            handleMenuClose();
        }
    };

    const handleEditInBook = (e) => {
        e.stopPropagation();
        handleMenuClose();
        navigate(`/my-recipes/${myRecipeId}/edit`);
    };

    const handleEdit = (e) => {
        e.stopPropagation();
        handleMenuClose();
        navigate(`/my-recipes/${recipe.id}/edit`);
    };

    const handleDeleteClick = (e) => {
        e.stopPropagation();
        handleMenuClose();
        setDeleteDialogOpen(true);
    };

    const handleDeleteConfirm = async () => {
        try {
            await deleteMyRecipe(recipe.id);
            setDeleteDialogOpen(false);
            // Call onDeleted callback if provided, otherwise refresh
            if (onDeleted) {
                onDeleted(recipe.id);
            } else {
                window.location.reload();
            }
        } catch (err) {
            console.error('Delete failed:', err);
            alert('Failed to delete recipe');
            setDeleteDialogOpen(false);
        }
    };

    const handleDeleteCancel = () => {
        setDeleteDialogOpen(false);
    };

    const handleRatingClick = (e) => {
        e.stopPropagation();
        handleMenuClose();
        setRatingDialogOpen(true);
    };

    const handleRatingSubmit = async () => {
        try {
            await upsertRating({
                recipeId: recipe.id,
                userId: user.id,
                stars: userRating,
                recipeTitle: recipe.title,
                recipeImage: recipe.image
            });
            setRatingDialogOpen(false);
        } catch (err) {
            console.error('Rating failed:', err);
            alert('Failed to submit rating');
        }
    };

    const handleCommentClick = (e) => {
        e.stopPropagation();
        handleMenuClose();
        setCommentDialogOpen(true);
    };

    const handleCommentSubmit = async () => {
        if (!newComment.trim()) return;
        try {
            await addComment({
                recipeId: recipe.id,
                userId: user.id,
                userName: user.name,
                text: newComment.trim()
            });
            setNewComment('');
            setCommentDialogOpen(false);
        } catch (err) {
            console.error('Comment failed:', err);
            alert('Failed to add comment');
        }
    };

    return (
        <Card
            sx={{
                flex: 1,
                display: 'flex',
                flexDirection: 'column',
                transition: 'all 0.3s ease-in-out',
                '&:hover': {
                    transform: 'scale(1.02)',
                    boxShadow: '0 12px 40px rgba(0,0,0,0.2)',
                    zIndex: 10
                },
                borderRadius: 1.5,
                overflow: 'hidden',
                boxShadow: '0 8px 24px rgba(0,0,0,0.08)',
                position: 'relative',
                bgcolor: 'white'
            }}
        >
            <Tooltip title={user ? '' : 'Please log in to view full recipe details'} arrow disableHoverListener={Boolean(user)}>
                <Box
                    onClick={handleClick}
                    sx={{
                        height: '100%',
                        display: 'flex',
                        flexDirection: 'column',
                        alignItems: 'stretch',
                        cursor: 'pointer'
                    }}
                >
                    <Box sx={{ position: 'relative', paddingTop: '66.67%' }}>
                        <CardMedia
                            component="img"
                            image={recipe.image}
                            alt={recipe.title}
                            sx={{
                                position: 'absolute',
                                top: 0,
                                left: 0,
                                width: '100%',
                                height: '100%',
                                objectFit: 'cover'
                            }}
                        />
                        <Box
                            sx={{
                                position: 'absolute',
                                top: 0,
                                left: 0,
                                right: 0,
                                bottom: 0,
                                background: 'linear-gradient(180deg, rgba(0,0,0,0) 0%, rgba(0,0,0,0) 60%, rgba(0,0,0,0.6) 100%)',
                                zIndex: 1
                            }}
                        />
                        {typeof rating === 'number' && (
                            <Box sx={{
                                position: 'absolute',
                                top: 12,
                                right: 12,
                                zIndex: 2,
                                display: 'flex',
                                alignItems: 'center',
                                gap: 0.5,
                                backgroundColor: 'white',
                                borderRadius: 2,
                                px: 0.75,
                                py: 0.25,
                                boxShadow: '0 2px 8px rgba(0,0,0,0.1)'
                            }} onClick={(e) => e.stopPropagation()}>
                                <StarIcon sx={{ fontSize: '1rem', color: 'goldenrod' }} />
                                <Typography variant="caption" sx={{ fontWeight: 600 }}>{rating.toFixed(1)}</Typography>
                            </Box>
                        )}
                        <IconButton
                            onClick={handleToggleFavorite}
                            size="small"
                            sx={{
                                position: 'absolute',
                                top: typeof rating === 'number' ? 40 : 12,
                                right: 12,
                                backgroundColor: 'white',
                                boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
                                zIndex: 2,
                                padding: 0.5,
                                '&:hover': {
                                    backgroundColor: 'white',
                                    transform: 'scale(1.1)'
                                }
                            }}
                        >
                            <FavoriteIcon
                                sx={{
                                    fontSize: '1rem',
                                    color: fav ? '#FF9F00' : 'action.disabled'
                                }}
                            />
                        </IconButton>
                        {/* Options menu: add to my recipe book - only show if user is logged in */}
                        {user && (
                            <IconButton
                                aria-label={`More options for ${recipe.title}`}
                                onClick={handleMenuOpen}
                                size="small"
                                sx={{
                                    position: 'absolute',
                                    bottom: 12,
                                    right: 12,
                                    backgroundColor: 'secondary.main',
                                    color: 'white',
                                    boxShadow: '0 2px 8px rgba(0,0,0,0.2)',
                                    zIndex: 2,
                                    padding: 0.5,
                                    '&:hover': {
                                        backgroundColor: 'secondary.dark'
                                    }
                                }}
                            >
                                <MoreVertIcon fontSize="small" />
                            </IconButton>
                        )}
                        <Menu
                            anchorEl={menuAnchor}
                            open={Boolean(menuAnchor)}
                            onClose={handleMenuClose}
                            anchorOrigin={{ vertical: 'top', horizontal: 'right' }}
                            transformOrigin={{ vertical: 'bottom', horizontal: 'right' }}
                            slotProps={{
                                paper: {
                                    sx: {
                                        '& .MuiMenuItem-root': {
                                            fontSize: '0.75rem',
                                            py: 0
                                        }
                                    }
                                }
                            }}
                        >
                            {isMyRecipe ? (
                                [
                                    <MenuItem key="edit" onClick={handleEdit}>Edit</MenuItem>,
                                    <MenuItem key="delete" onClick={handleDeleteClick}>Delete</MenuItem>
                                ]
                            ) : (
                                [
                                    // Recipe management options
                                    myRecipeId ? (
                                        <MenuItem key="edit-in-book" onClick={handleEditInBook}>Edit in My Recipe Book</MenuItem>
                                    ) : (
                                        <MenuItem key="add-to-book" onClick={handleAddToBook}>Add to My Recipe Book</MenuItem>
                                    ),
                                    // Rating and comment options for all external recipes
                                    <MenuItem key="rate" onClick={handleRatingClick}>
                                        <RateReviewIcon sx={{ mr: 1, fontSize: '1rem' }} />
                                        Rate Recipe
                                    </MenuItem>,
                                    <MenuItem key="comment" onClick={handleCommentClick}>
                                        <CommentIcon sx={{ mr: 1, fontSize: '1rem' }} />
                                        Add Comment
                                    </MenuItem>
                                ]
                            )}
                        </Menu>

                        {/* Delete Confirmation Dialog */}
                        <Dialog
                            open={deleteDialogOpen}
                            onClose={handleDeleteCancel}
                            aria-labelledby="delete-dialog-title"
                            aria-describedby="delete-dialog-description"
                        >
                            <DialogTitle id="delete-dialog-title">Delete Recipe?</DialogTitle>
                            <DialogContent>
                                <DialogContentText id="delete-dialog-description">
                                    Are you sure you want to delete "{recipe.title}"? This action cannot be undone.
                                </DialogContentText>
                            </DialogContent>
                            <DialogActions>
                                <Button onClick={handleDeleteCancel} color="primary">
                                    Cancel
                                </Button>
                                <Button onClick={handleDeleteConfirm} color="error" variant="contained" autoFocus>
                                    Delete
                                </Button>
                            </DialogActions>
                        </Dialog>

                        {/* Rating Dialog */}
                        <Dialog
                            open={ratingDialogOpen}
                            onClose={() => setRatingDialogOpen(false)}
                            aria-labelledby="rating-dialog-title"
                            maxWidth="sm"
                            fullWidth
                            onClick={(e) => e.stopPropagation()}
                        >
                            <DialogTitle id="rating-dialog-title">Rate Recipe</DialogTitle>
                            <DialogContent>
                                <Box sx={{ textAlign: 'center', py: 2 }}>
                                    <Typography variant="h6" sx={{ mb: 2 }}>{recipe.title}</Typography>
                                    <Rating
                                        value={userRating}
                                        onChange={(_, newValue) => setUserRating(newValue || 0)}
                                        size="large"
                                        sx={{ mb: 2 }}
                                    />
                                    <Typography variant="body2" color="text.secondary">
                                        {userRating > 0 ? `You rated this recipe ${userRating} star${userRating !== 1 ? 's' : ''}` : 'Select a rating'}
                                    </Typography>
                                </Box>
                            </DialogContent>
                            <DialogActions>
                                <Button onClick={() => setRatingDialogOpen(false)}>Cancel</Button>
                                <Button
                                    onClick={handleRatingSubmit}
                                    variant="contained"
                                    disabled={userRating === 0}
                                >
                                    Submit Rating
                                </Button>
                            </DialogActions>
                        </Dialog>

                        {/* Comment Dialog */}
                        <Dialog
                            open={commentDialogOpen}
                            onClose={() => setCommentDialogOpen(false)}
                            aria-labelledby="comment-dialog-title"
                            maxWidth="sm"
                            fullWidth
                            onClick={(e) => e.stopPropagation()}
                        >
                            <DialogTitle id="comment-dialog-title">Add Comment</DialogTitle>
                            <DialogContent>
                                <Box sx={{ py: 1 }}>
                                    <Typography variant="h6" sx={{ mb: 2 }}>{recipe.title}</Typography>
                                    <TextField
                                        autoFocus
                                        label="Your comment"
                                        multiline
                                        rows={4}
                                        fullWidth
                                        variant="outlined"
                                        value={newComment}
                                        onChange={(e) => setNewComment(e.target.value)}
                                        placeholder="Share your thoughts about this recipe..."
                                    />
                                </Box>
                            </DialogContent>
                            <DialogActions>
                                <Button onClick={() => setCommentDialogOpen(false)}>Cancel</Button>
                                <Button
                                    onClick={handleCommentSubmit}
                                    variant="contained"
                                    disabled={!newComment.trim()}
                                >
                                    Add Comment
                                </Button>
                            </DialogActions>
                        </Dialog>
                    </Box>
                    <CardContent sx={{ flexGrow: 1, display: 'flex', flexDirection: 'column', p: 2 }}>
                        <Typography
                            variant="h6"
                            component="div"
                            sx={{
                                fontWeight: 600,
                                fontSize: '1.1rem',
                                overflow: 'hidden',
                                textOverflow: 'ellipsis',
                                display: '-webkit-box',
                                WebkitLineClamp: 1,
                                WebkitBoxOrient: 'vertical',
                                mb: 1,
                                lineHeight: 1.3
                            }}
                        >
                            {recipe.title}
                        </Typography>
                        <Typography
                            variant="body2"
                            sx={{
                                color: 'text.secondary',
                                overflow: 'hidden',
                                textOverflow: 'ellipsis',
                                display: '-webkit-box',
                                WebkitLineClamp: 2,
                                WebkitBoxOrient: 'vertical',
                                mb: 1.5,
                                lineHeight: 1.5,
                                fontSize: '0.875rem'
                            }}
                        >
                            {stripHtml(recipe.summary)}
                        </Typography>
                        <Box sx={{
                            display: 'flex',
                            gap: 2,
                            mt: 'auto'
                        }}>
                            {recipe.readyInMinutes && (
                                <Typography
                                    variant="body2"
                                    sx={{
                                        display: 'flex',
                                        alignItems: 'center',
                                        gap: 0.5,
                                        color: 'text.secondary',
                                        fontSize: '0.875rem'
                                    }}
                                >
                                    ⏱️ {recipe.readyInMinutes} min
                                </Typography>
                            )}
                            {recipe.servings && (
                                <Typography
                                    variant="body2"
                                    sx={{
                                        display: 'flex',
                                        alignItems: 'center',
                                        gap: 0.5,
                                        color: 'text.secondary',
                                        fontSize: '0.875rem'
                                    }}
                                >
                                    👥 {recipe.servings} servings
                                </Typography>
                            )}
                        </Box>
                    </CardContent>
                </Box>
            </Tooltip>

            {/* Share Prompt Dialog */}
            <Dialog
                open={sharePromptOpen}
                onClose={shareLoading ? null : handleSharePromptNo}
                onClick={(e) => e.stopPropagation()}
            >
                <DialogTitle>
                    {shareSuccess ? 'Recipe Shared!' : 'Would you share this recipe?'}
                </DialogTitle>
                <DialogContent>
                    <DialogContentText>
                        {shareSuccess
                            ? `"${recipe.title}" has been shared with the community successfully! ✓`
                            : `You've added "${recipe.title}" to your favorites! Would you like to share this recipe with others?`
                        }
                    </DialogContentText>
                </DialogContent>
                <DialogActions>
                    {!shareSuccess && (
                        <>
                            <Button onClick={handleSharePromptNo} color="inherit" disabled={shareLoading}>
                                No, Thanks
                            </Button>
                            <Button
                                onClick={handleSharePromptYes}
                                variant="contained"
                                color="primary"
                                disabled={shareLoading}
                            >
                                {shareLoading ? 'Sharing...' : 'Yes, Share'}
                            </Button>
                        </>
                    )}
                </DialogActions>
            </Dialog>
        </Card>
    );
}

export default RecipeCard;
