// react-meal-planner/react-recipes/src/pages/RecipeDetail.js
import React, { useEffect, useState } from 'react';
import { useParams, useNavigate, useLocation } from 'react-router-dom';
import { Box, Typography, Container, Button, List, ListItem, ListItemText, Divider, Alert, CircularProgress, IconButton } from '@mui/material';
import { ArrowBack } from '@mui/icons-material';
import { getRecipeDetails } from '../services/recipeService';
import { useAuth } from '../context/AuthContext';
import api from '../services/jsonServerAPI';
import { createMarkup } from '../utils/htmlUtils';

function RecipeDetail({ isCustomRecipe = false }) {
    const { id } = useParams();
    const navigate = useNavigate();
    const location = useLocation();
    const { user } = useAuth();
    const [recipe, setRecipe] = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);

    useEffect(() => {
        let mounted = true;
        const load = async () => {
            setLoading(true);
            setError(null);
            try {
                let data;
                if (isCustomRecipe) {
                    // Fetch from myRecipes API
                    const res = await api.get(`/myRecipes/${id}`);
                    data = res.data;

                    // Transform custom recipe data to match expected format
                    data = {
                        ...data,
                        // Parse string instructions/ingredients back if needed for display
                        instructions: data.instructions || '',
                        ingredients: data.ingredients || ''
                    };
                } else {
                    // Fetch from Spoonacular API
                    data = await getRecipeDetails(id);
                }

                if (mounted) setRecipe(data);
            } catch (err) {
                if (mounted) setError(err.message || 'Failed to load recipe');
            } finally {
                if (mounted) setLoading(false);
            }
        };
        load();
        return () => { mounted = false };
    }, [id, isCustomRecipe]);

    if (loading) return (
        <Box sx={{ display: 'flex', justifyContent: 'center', mt: 6 }}>
            <CircularProgress />
        </Box>
    );

    if (error) return (
        <Container sx={{ py: 6 }}>
            <Alert severity="error">{error}</Alert>
        </Container>
    );

    if (!recipe) return null;

    return (
        <Container maxWidth="lg" sx={{ py: 6, pt: 12 }}>
            {/* Back Button */}
            <Box sx={{ mb: 2 }}>
                <IconButton
                    onClick={() => {
                        // Check if we came from meal planner
                        if (location.state?.from === '/meal-planner') {
                            navigate('/meal-planner');
                        } else {
                            navigate(-1);
                        }
                    }}
                    sx={{
                        color: 'text.secondary',
                        '&:hover': { backgroundColor: 'action.hover' }
                    }}
                >
                    <ArrowBack />
                </IconButton>
                {location.state?.fromName && (
                    <Typography variant="body2" component="span" sx={{ ml: 1, color: 'text.secondary' }}>
                        Back to {location.state.fromName}
                    </Typography>
                )}
            </Box>

            {/* Recipe Header */}
            <Box sx={{ mb: 4 }}>
                <img src={recipe.image} alt={recipe.title} style={{ width: '100%', maxHeight: '400px', borderRadius: 12, objectFit: 'cover' }} />
                <Typography variant="h3" sx={{ mt: 3, mb: 1, fontWeight: 600 }}>{recipe.title}</Typography>
                {recipe.summary && (
                    <Typography
                        variant="body1"
                        color="text.secondary"
                        sx={{
                            mb: 2,
                            '& a': { color: 'primary.main', textDecoration: 'none', '&:hover': { textDecoration: 'underline' } },
                            '& b': { fontWeight: 600 }
                        }}
                        dangerouslySetInnerHTML={createMarkup(recipe.summary)}
                    />
                )}
            </Box>

            {user ? (
                <>
                    {/* Three Column Layout: Ingredients | Instructions | Nutrition */}
                    <Box sx={{ display: 'flex', gap: 3, flexDirection: { xs: 'column', md: 'row' }, mb: 4 }}>
                        {/* Ingredients */}
                        <Box sx={{ flex: 1 }}>
                            <Typography variant="h6" sx={{ mb: 2, fontWeight: 600 }}>Ingredients</Typography>
                            {recipe.extendedIngredients && recipe.extendedIngredients.length > 0 ? (
                                <List dense>
                                    {recipe.extendedIngredients.map(ing => (
                                        <ListItem key={ing.id} sx={{ pl: 0 }}>
                                            <ListItemText primary={ing.original || `${ing.amount || ''} ${ing.unit || ''} ${ing.name || ''}`} />
                                        </ListItem>
                                    ))}
                                </List>
                            ) : recipe.ingredients ? (
                                <Typography variant="body2" sx={{ whiteSpace: 'pre-line', lineHeight: 1.8 }}>{recipe.ingredients}</Typography>
                            ) : (
                                <Typography variant="body2" color="text.secondary">No ingredients available.</Typography>
                            )}
                        </Box>

                        {/* Instructions */}
                        <Box sx={{ flex: 1 }}>
                            <Typography variant="h6" sx={{ mb: 2, fontWeight: 600 }}>Instructions</Typography>
                            {recipe.instructions ? (
                                <Typography
                                    variant="body2"
                                    sx={{
                                        whiteSpace: 'pre-line',
                                        lineHeight: 1.8,
                                        '& a': { color: 'primary.main', textDecoration: 'none', '&:hover': { textDecoration: 'underline' } },
                                        '& b': { fontWeight: 600 },
                                        '& ol': { paddingLeft: 2 },
                                        '& li': { marginBottom: 1 }
                                    }}
                                    dangerouslySetInnerHTML={createMarkup(recipe.instructions)}
                                />
                            ) : (
                                <Typography variant="body2" color="text.secondary">No instructions available.</Typography>
                            )}
                        </Box>

                        {/* Nutrition Info */}
                        <Box sx={{ flex: 1 }}>
                            <Typography variant="h6" sx={{ mb: 2, fontWeight: 600 }}>Nutrition</Typography>
                            {recipe.nutrition ? (
                                <List dense>
                                    {recipe.nutrition.nutrients?.slice(0, 8).map((nutrient, idx) => (
                                        <ListItem key={idx} sx={{ pl: 0, py: 0.5 }}>
                                            <ListItemText
                                                primary={
                                                    <Box sx={{ display: 'flex', justifyContent: 'space-between' }}>
                                                        <Typography variant="body2">{nutrient.name}</Typography>
                                                        <Typography variant="body2" fontWeight={500}>
                                                            {nutrient.amount} {nutrient.unit}
                                                        </Typography>
                                                    </Box>
                                                }
                                            />
                                        </ListItem>
                                    ))}
                                </List>
                            ) : (
                                <Box>
                                    <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
                                        Basic nutrition per serving:
                                    </Typography>
                                    <List dense>
                                        {recipe.servings && (
                                            <ListItem sx={{ pl: 0, py: 0.5 }}>
                                                <ListItemText
                                                    primary={
                                                        <Box sx={{ display: 'flex', justifyContent: 'space-between' }}>
                                                            <Typography variant="body2">Servings</Typography>
                                                            <Typography variant="body2" fontWeight={500}>{recipe.servings}</Typography>
                                                        </Box>
                                                    }
                                                />
                                            </ListItem>
                                        )}
                                        {recipe.readyInMinutes && (
                                            <ListItem sx={{ pl: 0, py: 0.5 }}>
                                                <ListItemText
                                                    primary={
                                                        <Box sx={{ display: 'flex', justifyContent: 'space-between' }}>
                                                            <Typography variant="body2">Ready in</Typography>
                                                            <Typography variant="body2" fontWeight={500}>{recipe.readyInMinutes} min</Typography>
                                                        </Box>
                                                    }
                                                />
                                            </ListItem>
                                        )}
                                        <ListItem sx={{ pl: 0, py: 0.5 }}>
                                            <ListItemText
                                                primary={
                                                    <Typography variant="body2" color="text.secondary" fontStyle="italic">
                                                        Detailed nutrition info not available
                                                    </Typography>
                                                }
                                            />
                                        </ListItem>
                                    </List>
                                </Box>
                            )}
                        </Box>
                    </Box>
                </>
            ) : (
                <Box sx={{ mt: 3, mb: 4 }}>
                    <Alert severity="info">Please log in to view full recipe details (ingredients, instructions & nutrition).</Alert>
                    <Button variant="contained" sx={{ mt: 2 }} onClick={() => navigate('/login', { state: { from: window.location.pathname } })}>Log in</Button>
                </Box>
            )}
        </Container>
    );
}

export default RecipeDetail;

// angular-meal-planner/angular-recipes/src/app/pages/recipe-detail/recipe-detail.component.ts
import { Component, OnInit, OnDestroy, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router, RouterModule } from '@angular/router';
import { Location } from '@angular/common';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import { HttpClient } from '@angular/common/http';
import { Subscription, Observable } from 'rxjs';
import { RecipeService } from '../../services/recipe.service';
import { AuthService } from '../../services/auth.service';
import { environment } from '../../../environments/environment';
import { stripHtml } from '../../utils/html-utils';

@Component({
    selector: 'app-recipe-detail',
    standalone: true,
    imports: [CommonModule, RouterModule],
    templateUrl: './recipe-detail.component.html',
    styleUrls: ['./recipe-detail.component.scss']
})
export class RecipeDetailComponent implements OnInit, OnDestroy {
    recipe: any = null;
    loading = true;
    error: string | null = null;
    user$: Observable<any>;
    isCustomRecipe = false;
    private subscriptions: Subscription[] = [];

    constructor(
        private route: ActivatedRoute,
        private router: Router,
        private location: Location,
        private sanitizer: DomSanitizer,
        private http: HttpClient,
        private recipeService: RecipeService,
        private authService: AuthService,
        private cdr: ChangeDetectorRef
    ) {
        this.user$ = this.authService.user$;
    }

    ngOnInit() {
        // Get route data to determine if this is a custom recipe
        this.isCustomRecipe = this.route.snapshot.data['isCustomRecipe'] || false;

        // Get recipe ID from route params
        const routeSub = this.route.params.subscribe(params => {
            const id = params['id'];
            if (id) {
                this.loadRecipe(id);
            }
        });
        this.subscriptions.push(routeSub);
    }

    ngOnDestroy() {
        this.subscriptions.forEach(sub => sub.unsubscribe());
    }

    async loadRecipe(id: string) {
        console.log('Loading recipe with ID:', id);
        this.loading = true;
        this.error = null;

        try {
            let data: any;

            if (this.isCustomRecipe) {
                console.log('Fetching custom recipe from myRecipes API');
                // Fetch from myRecipes API
                const response = await this.http.get<any>(
                    `${environment.jsonServerUrl}/myRecipes/${id}`
                ).toPromise();

                data = {
                    ...response,
                    // Ensure instructions and ingredients are strings for display
                    instructions: response.instructions || '',
                    ingredients: response.ingredients || ''
                };
            } else {
                console.log('Fetching recipe from RecipeService');
                // Fetch from Spoonacular API via RecipeService
                data = await this.recipeService.getRecipeDetails(Number(id));
            }

            console.log('Recipe data received:', data);
            this.recipe = data;
            this.loading = false;
            console.log('Loading set to false, recipe:', this.recipe);
            this.cdr.detectChanges();
        } catch (err: any) {
            console.error('Failed to load recipe:', err);
            this.error = err.message || 'Failed to load recipe';
            this.loading = false;
            this.cdr.detectChanges();
        }
    }

    goBack() {
        // Check if there's navigation state
        const state = this.location.getState() as any;

        if (state?.from === '/meal-planner') {
            this.router.navigate(['/meal-planner']);
        } else {
            this.location.back();
        }
    }

    sanitizeHtml(html: string): SafeHtml {
        return this.sanitizer.sanitize(1, html) || '';
    }

    getStrippedHtml(html: string): string {
        return stripHtml(html);
    }

    navigateToLogin() {
        this.router.navigate(['/login'], {
            state: { from: this.router.url }
        });
    }

    getBackButtonText(): string {
        const state = this.location.getState() as any;
        return state?.fromName || '';
    }

    get typeof() {
        return (val: any) => typeof val;
    }
}

<div class="recipe-detail-container">
    <!-- Loading State -->
    <div *ngIf="loading" class="loading-container">
        <div class="spinner"></div>
    </div>

    <!-- Error State -->
    <div *ngIf="error && !loading" class="error-container">
        <div class="alert alert-error">{{ error }}</div>
    </div>

    <!-- Recipe Content -->
    <div *ngIf="recipe && !loading" class="recipe-content">

        <!-- Back Button -->
        <div class="back-button-container">
            <button title="Go back" class="back-button" (click)="goBack()">
                <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24">
                    <path d="M0 0h24v24H0z" fill="none" />
                    <path d="M20 11H7.83l5.59-5.59L12 4l-8 8 8 8 1.41-1.41L7.83 13H20v-2z" />
                </svg>
            </button>
            <span *ngIf="getBackButtonText()" class="back-text">Back to {{ getBackButtonText() }}</span>
        </div>

        <!-- Recipe Header -->
        <div class="recipe-header">
            <img [src]="recipe.image" [alt]="recipe.title" class="recipe-image">
            <h1 class="recipe-title">{{ recipe.title }}</h1>
            <div *ngIf="recipe.summary" class="recipe-summary" [innerHTML]="sanitizeHtml(recipe.summary)">
            </div>
        </div>



        <!-- Authenticated Content -->
        <div *ngIf="user$ | async as user; else loginPrompt" class="detail-grid">
            <!-- Ingredients Column -->
            <div class="detail-column">
                <h2 class="column-title">Ingredients</h2>

                <!-- Extended Ingredients (from Spoonacular) -->
                <ul *ngIf="recipe.extendedIngredients?.length > 0" class="ingredients-list">
                    <li *ngFor="let ing of recipe.extendedIngredients" class="ingredient-item">
                        {{ ing.original || (ing.amount + ' ' + ing.unit + ' ' + ing.name) }}
                    </li>
                </ul>

                <!-- String Ingredients (from custom recipes) -->
                <div *ngIf="(!recipe.extendedIngredients || recipe.extendedIngredients.length === 0) && recipe.ingredients"
                    class="ingredients-text">
                    {{ recipe.ingredients }}
                </div>

                <!-- No Ingredients -->
                <p *ngIf="(!recipe.extendedIngredients || recipe.extendedIngredients.length === 0) && !recipe.ingredients"
                    class="no-content">
                    No ingredients available.
                </p>
            </div>

            <!-- Instructions Column -->
            <div class="detail-column">
                <h2 class="column-title">Instructions</h2>

                <div *ngIf="recipe.instructions" class="instructions-text"
                    [innerHTML]="sanitizeHtml(recipe.instructions)">
                </div>

                <p *ngIf="!recipe.instructions" class="no-content">
                    No instructions available.
                </p>
            </div>

            <!-- Nutrition Column -->
            <div class="detail-column">
                <h2 class="column-title">Nutrition</h2>

                <!-- Detailed Nutrition (from Spoonacular) -->
                <ul *ngIf="recipe.nutrition && recipe.nutrition.nutrients" class="nutrition-list">
                    <li *ngFor="let nutrient of recipe.nutrition.nutrients.slice(0, 8)" class="nutrition-item">
                        <span class="nutrient-name">{{ nutrient.name }}</span>
                        <span class="nutrient-value">{{ nutrient.amount }} {{ nutrient.unit }}</span>
                    </li>
                </ul>

                <!-- Basic Nutrition Fallback -->
                <div *ngIf="!recipe.nutrition || !recipe.nutrition.nutrients">
                    <p class="nutrition-subtitle">Basic nutrition per serving:</p>
                    <ul class="nutrition-list">
                        <li *ngIf="recipe.servings" class="nutrition-item">
                            <span class="nutrient-name">Servings</span>
                            <span class="nutrient-value">{{ recipe.servings }}</span>
                        </li>
                        <li *ngIf="recipe.readyInMinutes" class="nutrition-item">
                            <span class="nutrient-name">Ready in</span>
                            <span class="nutrient-value">{{ recipe.readyInMinutes }} min</span>
                        </li>
                        <li class="nutrition-item">
                            <span class="no-content-italic">Detailed nutrition info not available</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <!-- Unauthenticated Prompt -->
        <ng-template #loginPrompt>
            <div class="login-prompt">
                <div class="alert alert-info">
                    Please log in to view full recipe details (ingredients, instructions & nutrition).
                </div>
                <button class="login-button" (click)="navigateToLogin()">Log in</button>
            </div>
        </ng-template>
    </div>
</div>
