// react-meal-planner/react-recipes/src/pages/Login.js
import React, { useState, useEffect } from 'react';
import { Box, TextField, Button, Typography, Alert, Paper, Chip, FormControl, FormLabel, IconButton, Dialog, DialogTitle, DialogContent, DialogContentText, DialogActions } from '@mui/material';
import ArrowBackIcon from '@mui/icons-material/ArrowBack';
import { useNavigate, useLocation } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';

function Login() {
    const navigate = useNavigate();
    const location = useLocation();
    const { login, register } = useAuth();
    const [isLogin, setIsLogin] = useState(true);
    const [error, setError] = useState('');
    const [loading, setLoading] = useState(false);
    const [formData, setFormData] = useState({
        email: '',
        password: '',
        name: '',
        preferences: []
    });
    const [failedAttempts, setFailedAttempts] = useState(0);
    const [lockoutEndTime, setLockoutEndTime] = useState(null);
    const [remainingTime, setRemainingTime] = useState(0);
    const [isLocked, setIsLocked] = useState(false);
    const [showPasswordChangePrompt, setShowPasswordChangePrompt] = useState(false);
    const [wasLockedOut, setWasLockedOut] = useState(false);

    const preferenceOptions = [
        { label: 'Appetizers', value: 'appetizers' },
        { label: 'Main Course', value: 'main-course' },
        { label: 'Salads & Sides', value: 'salads-sides' },
        { label: 'Vegetarian', value: 'vegetarian' },
        { label: 'Breakfast', value: 'breakfast' },
        { label: 'Dessert', value: 'dessert' },
        { label: 'Soups', value: 'soups' },
        { label: 'Drinks', value: 'drinks' },
        { label: 'Quick & Easy', value: 'quick-easy' }
    ];

    // Check lockout status on component mount and set up timer
    useEffect(() => {
        const storedLockoutEnd = localStorage.getItem(`lockoutEnd_${formData.email}`);
        const storedAttempts = localStorage.getItem(`failedAttempts_${formData.email}`);

        if (storedLockoutEnd) {
            const lockoutEnd = parseInt(storedLockoutEnd, 10);
            const now = Date.now();

            if (now < lockoutEnd) {
                setLockoutEndTime(lockoutEnd);
                setIsLocked(true);
                setRemainingTime(Math.ceil((lockoutEnd - now) / 1000));
            } else {
                // Lockout expired, clear it
                localStorage.removeItem(`lockoutEnd_${formData.email}`);
                localStorage.removeItem(`failedAttempts_${formData.email}`);
            }
        }

        if (storedAttempts) {
            setFailedAttempts(parseInt(storedAttempts, 10));
        }
    }, [formData.email]);

    // Timer countdown for lockout
    useEffect(() => {
        if (!isLocked || !lockoutEndTime) return;

        const interval = setInterval(() => {
            const now = Date.now();
            const timeLeft = Math.ceil((lockoutEndTime - now) / 1000);

            if (timeLeft <= 0) {
                setIsLocked(false);
                setLockoutEndTime(null);
                setFailedAttempts(0);
                setWasLockedOut(true);
                localStorage.removeItem(`lockoutEnd_${formData.email}`);
                localStorage.removeItem(`failedAttempts_${formData.email}`);
                clearInterval(interval);
            } else {
                setRemainingTime(timeLeft);
            }
        }, 1000);

        return () => clearInterval(interval);
    }, [isLocked, lockoutEndTime, formData.email]);

    const formatTime = (seconds) => {
        const mins = Math.floor(seconds / 60);
        const secs = seconds % 60;
        return `${mins}:${secs.toString().padStart(2, '0')}`;
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        setError('');

        // Check if account is locked
        if (isLocked) {
            setError(`Account temporarily locked. Please wait ${formatTime(remainingTime)} before trying again.`);
            return;
        }

        setLoading(true);

        try {
            let userData;
            if (isLogin) {
                userData = await login(formData.email, formData.password);

                // Successful login - reset failed attempts
                localStorage.removeItem(`failedAttempts_${formData.email}`);
                localStorage.removeItem(`lockoutEnd_${formData.email}`);

                // If user was locked out, show password change prompt
                if (wasLockedOut) {
                    setShowPasswordChangePrompt(true);
                    setWasLockedOut(false);
                    setLoading(false);
                    return;
                }
            } else {
                userData = await register(formData.email, formData.password, formData.name, formData.preferences);
            }

            // Determine redirect path based on user role
            let redirectTo;
            if (userData && userData.isAdmin) {
                // Admin users go to admin dashboard
                redirectTo = '/admin-dashboard';
            } else {
                // Regular users go to intended location or home
                redirectTo = (location.state && location.state.from) ? location.state.from : '/';
            }

            navigate(redirectTo, { replace: true });
        } catch (err) {
            setError(err.message);

            // Only track failed attempts for login (not registration)
            if (isLogin) {
                const newAttempts = failedAttempts + 1;
                setFailedAttempts(newAttempts);
                localStorage.setItem(`failedAttempts_${formData.email}`, newAttempts.toString());

                if (newAttempts >= 3) {
                    // Lock account for 2 minutes (120,000 milliseconds)
                    const lockoutEnd = Date.now() + 120000;
                    setLockoutEndTime(lockoutEnd);
                    setIsLocked(true);
                    setRemainingTime(120);
                    localStorage.setItem(`lockoutEnd_${formData.email}`, lockoutEnd.toString());
                    setError('Too many failed attempts. Account locked for 2 minutes.');
                } else {
                    setError(`${err.message} (Attempt ${newAttempts}/3)`);
                }
            }
        } finally {
            setLoading(false);
        }
    };

    const handlePasswordChangeYes = () => {
        setShowPasswordChangePrompt(false);
        navigate('/change-password');
    };

    const handlePasswordChangeNo = () => {
        setShowPasswordChangePrompt(false);
        // Proceed with normal navigation
        let redirectTo;
        if (location.state && location.state.from) {
            redirectTo = location.state.from;
        } else {
            redirectTo = '/';
        }
        navigate(redirectTo, { replace: true });
    };

    const handleChange = (e) => {
        setFormData({
            ...formData,
            [e.target.name]: e.target.value
        });
    };

    const handlePreferenceToggle = (value) => {
        setFormData(prev => ({
            ...prev,
            preferences: prev.preferences.includes(value)
                ? prev.preferences.filter(p => p !== value)
                : [...prev.preferences, value]
        }));
    };

    // Check if user came from another page
    const fromPage = location.state?.from;
    const showBackArrow = fromPage && fromPage !== '/login';

    const handleBackClick = () => {
        if (fromPage) {
            navigate(fromPage);
        } else {
            navigate(-1); // Go back in history
        }
    };

    return (
        <Box
            sx={{
                display: 'flex',
                justifyContent: 'center',
                alignItems: 'center',
                minHeight: 'calc(100vh - 64px)', // Subtract navbar height
                p: 2
            }}
        >
            <Paper elevation={3} sx={{ p: 4, maxWidth: 400, width: '100%', position: 'relative' }}>
                {/* Back Arrow - shown when coming from another page */}
                {showBackArrow && (
                    <IconButton
                        onClick={handleBackClick}
                        sx={{
                            position: 'absolute',
                            top: 16,
                            left: 16,
                            color: 'primary.main',
                            '&:hover': {
                                backgroundColor: 'rgba(255, 159, 41, 0.1)'
                            }
                        }}
                        aria-label="back to previous page"
                    >
                        <ArrowBackIcon />
                    </IconButton>
                )}

                <Typography variant="h5" component="h1" gutterBottom sx={{ pl: showBackArrow ? 5 : 0 }}>
                    {isLogin ? 'Login' : 'Register'}
                </Typography>

                {error && (
                    <Alert severity="error" sx={{ mb: 2 }}>
                        {error}
                    </Alert>
                )}

                <Box component="form" onSubmit={handleSubmit}>
                    {!isLogin && (
                        <>
                            <TextField
                                fullWidth
                                label="Name"
                                name="name"
                                value={formData.name}
                                onChange={handleChange}
                                margin="normal"
                                required
                            />

                            <FormControl fullWidth margin="normal" sx={{ mb: 2 }}>
                                <FormLabel sx={{ mb: 1, fontSize: '0.875rem', color: 'text.primary' }}>
                                    Dietary Preferences (Optional)
                                </FormLabel>
                                <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 1 }}>
                                    {preferenceOptions.map((pref) => (
                                        <Chip
                                            key={pref.value}
                                            label={pref.label}
                                            onClick={() => handlePreferenceToggle(pref.value)}
                                            color={formData.preferences.includes(pref.value) ? "primary" : "default"}
                                            sx={{ cursor: 'pointer' }}
                                        />
                                    ))}
                                </Box>
                            </FormControl>
                        </>
                    )}

                    <TextField
                        fullWidth
                        label="Email"
                        type="email"
                        name="email"
                        value={formData.email}
                        onChange={handleChange}
                        margin="normal"
                        required
                    />

                    <TextField
                        fullWidth
                        label="Password"
                        type="password"
                        name="password"
                        value={formData.password}
                        onChange={handleChange}
                        margin="normal"
                        required
                    />

                    <Button
                        fullWidth
                        type="submit"
                        variant="contained"
                        sx={{ mt: 3 }}
                        disabled={loading || isLocked}
                    >
                        {isLocked ? `Locked (${formatTime(remainingTime)})` : (isLogin ? 'Login' : 'Register')}
                    </Button>

                    <Button
                        fullWidth
                        onClick={() => {
                            setIsLogin(!isLogin);
                            setError('');
                        }}
                        sx={{ mt: 1 }}
                        disabled={isLocked}
                    >
                        {isLogin
                            ? "Don't have an account? Register"
                            : 'Already have an account? Login'}
                    </Button>
                </Box>
            </Paper>

            {/* Password Change Prompt Dialog */}
            <Dialog
                open={showPasswordChangePrompt}
                onClose={() => { }}
                aria-labelledby="password-change-dialog-title"
                aria-describedby="password-change-dialog-description"
            >
                <DialogTitle id="password-change-dialog-title">
                    Change Password Recommended
                </DialogTitle>
                <DialogContent>
                    <DialogContentText id="password-change-dialog-description">
                        Your account was temporarily locked due to multiple failed login attempts.
                        For security reasons, we recommend changing your password. Would you like to change it now?
                    </DialogContentText>
                </DialogContent>
                <DialogActions>
                    <Button onClick={handlePasswordChangeNo} color="inherit">
                        No, Thanks
                    </Button>
                    <Button onClick={handlePasswordChangeYes} variant="contained" color="primary" autoFocus>
                        Yes, Change Password
                    </Button>
                </DialogActions>
            </Dialog>
        </Box>
    );
}

export default Login;

// angular-meal-planner/angular-recipes/src/app/pages/login/login.component.ts
import { Component, OnInit, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, ActivatedRoute } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { firstValueFrom } from 'rxjs';

@Component({
    selector: 'app-login',
    standalone: true,
    imports: [CommonModule, ReactiveFormsModule],
    templateUrl: './login.component.html',
    styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {
    loginForm: FormGroup;
    isLogin = true;
    loading = false;
    error = '';
    showPasswordChangePrompt = false;
    isBlockedUser = false; // Flag to track blocked user state

    // Lockout state
    isLocked = false;
    lockoutEndTime: number | null = null;
    remainingTime = 0;

    preferenceOptions = [
        { value: 'vegetarian', label: 'Vegetarian' },
        { value: 'vegan', label: 'Vegan' },
        { value: 'glutenFree', label: 'Gluten Free' },
        { value: 'dairyFree', label: 'Dairy Free' }
    ];

    showBackArrow = false;
    private fromPage: string | null = null;

    constructor(
        private fb: FormBuilder,
        private authService: AuthService,
        private router: Router,
        private route: ActivatedRoute,
        private cdr: ChangeDetectorRef
    ) {
        this.loginForm = this.fb.group({
            email: ['', [Validators.required, Validators.email]],
            password: ['', Validators.required],
            name: [''],
            preferences: [[]]
        });
    }

    ngOnInit() {
        // Check for existing lockout
        const email = this.loginForm.get('email')?.value;
        if (email) {
            this.checkLockout(email);
        }

        // Check navigation state and query params
        const state = history.state;
        this.fromPage = state?.from || this.route.snapshot.queryParams['returnUrl'] || null;
        this.showBackArrow = !!this.fromPage && this.fromPage !== '/login';

        // Monitor email changes to check lockout status
        this.loginForm.get('email')?.valueChanges.subscribe(email => {
            this.checkLockout(email);
        });
    }

    checkLockout(email: string) {
        if (!email) return;
        const lockoutEndStr = localStorage.getItem(`lockoutEnd_${email}`);
        if (lockoutEndStr) {
            const lockoutEnd = parseInt(lockoutEndStr, 10);
            if (lockoutEnd > Date.now()) {
                this.isLocked = true;
                this.lockoutEndTime = lockoutEnd;
                this.updateRemainingTime();
                // Start timer
                const interval = setInterval(() => {
                    this.updateRemainingTime();
                    if (!this.isLocked) {
                        clearInterval(interval);
                        this.showPasswordChangePrompt = true;
                    }
                }, 1000);
            } else {
                localStorage.removeItem(`lockoutEnd_${email}`);
                this.isLocked = false;
            }
        }
    }

    updateRemainingTime() {
        if (this.lockoutEndTime) {
            const remaining = Math.ceil((this.lockoutEndTime - Date.now()) / 1000);
            if (remaining > 0) {
                this.remainingTime = remaining;
            } else {
                this.isLocked = false;
                this.lockoutEndTime = null;
                this.remainingTime = 0;
            }
        }
    }

    formatTime(seconds: number): string {
        const m = Math.floor(seconds / 60);
        const s = seconds % 60;
        return `${m}:${s.toString().padStart(2, '0')}`;
    }

    toggleMode() {
        this.isLogin = !this.isLogin;
        this.error = '';
        if (!this.isLogin) {
            this.loginForm.get('name')?.setValidators(Validators.required);
        } else {
            this.loginForm.get('name')?.clearValidators();
        }
        this.loginForm.get('name')?.updateValueAndValidity();
    }

    isPreferenceSelected(value: string): boolean {
        const prefs = this.loginForm.get('preferences')?.value || [];
        return prefs.includes(value);
    }

    handlePreferenceToggle(value: string) {
        const currentPrefs = this.loginForm.get('preferences')?.value || [];
        const index = currentPrefs.indexOf(value);
        if (index === -1) {
            this.loginForm.patchValue({ preferences: [...currentPrefs, value] });
        } else {
            this.loginForm.patchValue({ preferences: currentPrefs.filter((p: string) => p !== value) });
        }
    }

    async handleSubmit() {
        console.log('[LoginComponent] ===== HANDLE SUBMIT CALLED =====')
        console.log('[LoginComponent] Form valid:', this.loginForm.valid);
        console.log('[LoginComponent] isLogin:', this.isLogin);
        console.log('[LoginComponent] Current error:', this.error);
        console.log('[LoginComponent] Current loading:', this.loading);

        if (this.loginForm.invalid) {
            console.log('[LoginComponent] Form invalid, returning');
            return;
        }

        console.log('[LoginComponent] Setting loading to true, clearing error');
        this.loading = true;
        this.error = '';
        const formData = this.loginForm.value;
        console.log('[LoginComponent] Form data email:', formData.email);

        try {
            if (this.isLogin) {
                const email = formData.email;
                const attemptsKey = `loginAttempts_${email}`;

                try {
                    // Attempt login with actual API
                    console.log('[LoginComponent] ===== STARTING LOGIN API CALL =====');
                    console.log('[LoginComponent] Attempting login for:', formData.email);
                    console.log('[LoginComponent] Calling authService.login()');

                    const user = await firstValueFrom(this.authService.login({ email: formData.email, password: formData.password }));

                    console.log('[LoginComponent] ===== LOGIN API CALL SUCCEEDED =====');
                    console.log('[LoginComponent] User:', user.email, 'isAdmin:', user.isAdmin, 'isBlocked:', user.isBlocked);

                    // Success - clear failed attempts
                    localStorage.removeItem(attemptsKey);

                    // Navigate based on user role
                    let redirectTo: string;
                    if (user && user.isAdmin) {
                        // Admin user - redirect to home page
                        redirectTo = '/';
                    } else {
                        // Regular user - use fromPage if it's safe, otherwise default to root
                        // Avoid redirecting to admin pages
                        if (this.fromPage && !this.fromPage.startsWith('/admin') && !this.fromPage.startsWith('/dashboard')) {
                            redirectTo = this.fromPage;
                        } else {
                            redirectTo = '/';
                        }
                    }
                    this.router.navigate([redirectTo], { replaceUrl: true });

                } catch (loginError: any) {
                    console.log('[LoginComponent] ===== LOGIN ERROR CAUGHT =====');
                    console.log('[LoginComponent] Error object:', loginError);
                    console.log('[LoginComponent] Error message:', loginError.message);
                    console.log('[LoginComponent] Error type:', typeof loginError.message);

                    // Check if this is a blocked user error
                    const isBlockedError = loginError.message && loginError.message.includes('blocked');
                    console.log('[LoginComponent] Is blocked error?', isBlockedError);

                    if (isBlockedError) {
                        console.log('[LoginComponent] ===== BLOCKED USER DETECTED =====');
                        console.log('[LoginComponent] Before setting - loading:', this.loading, 'error:', this.error);

                        // Clear failed login attempts and lockout for blocked user
                        console.log('[LoginComponent] Clearing login attempts and lockout for blocked user');
                        localStorage.removeItem(attemptsKey);
                        localStorage.removeItem(`lockoutEnd_${email}`);
                        this.isLocked = false;
                        this.lockoutEndTime = null;
                        this.remainingTime = 0;

                        // IMPORTANT: Clear any session to prevent app from redirecting
                        console.log('[LoginComponent] Clearing user session to prevent redirects');
                        this.authService.logout();

                        // Set blocked flag
                        this.isBlockedUser = true;

                        // Stop loading immediately and show error
                        this.loading = false;
                        this.error = loginError.message;

                        console.log('[LoginComponent] After setting - loading:', this.loading, 'error:', this.error);
                        console.log('[LoginComponent] Error message length:', this.error.length);
                        console.log('[LoginComponent] isBlockedUser flag set to:', this.isBlockedUser);

                        // Force Angular to detect changes and update the UI
                        console.log('[LoginComponent] Forcing change detection');
                        this.cdr.detectChanges();

                        // Visual confirmation for debugging
                        console.log('[LoginComponent] DOM should now show error message');
                        console.log('[LoginComponent] Error will display for 5 seconds before redirect');
                        console.log('[LoginComponent] Current time:', new Date().toLocaleTimeString());

                        // Wait 5 seconds to show the error, then redirect to guest page
                        setTimeout(() => {
                            console.log('[LoginComponent] === 5 SECONDS ELAPSED ===');
                            console.log('[LoginComponent] Redirect time:', new Date().toLocaleTimeString());
                            console.log('[LoginComponent] Clearing error and redirecting to guest home page');
                            this.error = '';
                            this.isBlockedUser = false;
                            this.router.navigate(['/'], { replaceUrl: true });
                        }, 5000);

                        console.log('[LoginComponent] Blocked error handler complete, staying on login page to show message');
                        return;
                    }

                    console.log('[LoginComponent] Not a blocked error, continuing with normal error handling');

                    // Login failed - track attempts
                    const attempts = parseInt(localStorage.getItem(attemptsKey) || '0', 10);
                    const newAttempts = attempts + 1;
                    localStorage.setItem(attemptsKey, newAttempts.toString());

                    if (newAttempts >= 3) {
                        const lockoutEnd = Date.now() + 120000; // 2 minutes
                        localStorage.setItem(`lockoutEnd_${email}`, lockoutEnd.toString());
                        this.checkLockout(email);
                        throw new Error('Too many failed attempts. Account locked for 2 minutes.');
                    }

                    throw loginError;
                }
            } else {
                // Registration - wait for the entire observable chain to complete
                console.log('[LoginComponent] Starting registration...');
                const user = await firstValueFrom(this.authService.register({
                    name: formData.name,
                    email: formData.email,
                    password: formData.password,
                    preferences: formData.preferences || []
                }));
                console.log('[LoginComponent] Registration completed, user:', user);

                // Navigate only after registration completes
                const redirectTo = this.fromPage || '/';
                this.router.navigate([redirectTo], { replaceUrl: true });
            }

        } catch (e: any) {
            console.log('[LoginComponent] ===== OUTER CATCH BLOCK =====');
            console.log('[LoginComponent] Outer error:', e);
            console.log('[LoginComponent] Outer error message:', e.message);
            this.error = e.message || 'An error occurred';
            console.log('[LoginComponent] Error set in outer catch:', this.error);
        } finally {
            console.log('[LoginComponent] ===== FINALLY BLOCK =====');
            console.log('[LoginComponent] isBlockedUser flag:', this.isBlockedUser);
            console.log('[LoginComponent] Current error before finally:', this.error);
            console.log('[LoginComponent] Current loading before finally:', this.loading);

            // Only set loading to false if not a blocked user (already handled)
            if (!this.isBlockedUser) {
                console.log('[LoginComponent] Not blocked user, setting loading to false');
                this.loading = false;
            } else {
                console.log('[LoginComponent] Blocked user - keeping loading state as is');
            }

            console.log('[LoginComponent] Loading is now:', this.loading);
            console.log('[LoginComponent] Error is now:', this.error);
        }
    }

    handleBackClick() {
        console.log('[LoginComponent] Back button clicked');

        // Check if current user is blocked
        const currentUser = this.authService.getCurrentUser();
        if (currentUser?.isBlocked) {
            console.log('[LoginComponent] User is blocked, clearing session');
            this.authService.logout();
            this.error = 'Your account has been blocked. Please contact the administrator.';
            return;
        }

        // Navigate back only if user is not blocked
        if (this.fromPage) {
            this.router.navigateByUrl(this.fromPage);
        } else {
            this.router.navigate(['/']);
        }
    }

    handlePasswordChangeYes() {
        this.showPasswordChangePrompt = false;
        this.router.navigate(['/change-password']);
    }

    handlePasswordChangeNo() {
        this.showPasswordChangePrompt = false;
        // Proceed with normal navigation
        const redirectTo = this.fromPage || '/';
        this.router.navigate([redirectTo], { replaceUrl: true });
    }
}

<div class="login-container">
    <div class="login-paper">
        <!-- Back Arrow -->
        <button *ngIf="showBackArrow" class="back-button" (click)="handleBackClick()"
            aria-label="back to previous page">
            <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24" fill="currentColor">
                <path d="M0 0h24v24H0z" fill="none" />
                <path d="M20 11H7.83l5.59-5.59L12 4l-8 8 8 8 1.41-1.41L7.83 13H20v-2z" />
            </svg>
        </button>

        <h1 [class.title-padded]="showBackArrow">{{ isLogin ? 'Login' : 'Register' }}</h1>

        <div *ngIf="error" class="alert alert-error">
            {{ error }}
        </div>

        <form [formGroup]="loginForm" (ngSubmit)="handleSubmit()">
            <ng-container *ngIf="!isLogin">
                <div class="form-field">
                    <input type="text" formControlName="name" placeholder="Name" required>
                </div>

                <div class="form-field">
                    <label class="form-label">Dietary Preferences (Optional)</label>
                    <div class="preferences-container">
                        <button type="button" *ngFor="let pref of preferenceOptions" class="chip"
                            [class.selected]="isPreferenceSelected(pref.value)"
                            (click)="handlePreferenceToggle(pref.value)">
                            {{ pref.label }}
                        </button>
                    </div>
                </div>
            </ng-container>

            <div class="form-field">
                <input type="email" formControlName="email" placeholder="Email" required>
            </div>

            <div class="form-field">
                <input type="password" formControlName="password" placeholder="Password" required>
            </div>

            <button type="submit" class="submit-button" [disabled]="loading || isLocked">
                {{ isLocked ? 'Locked (' + formatTime(remainingTime) + ')' : (isLogin ? 'Login' : 'Register') }}
            </button>

            <button type="button" class="toggle-button" (click)="toggleMode()" [disabled]="isLocked">
                {{ isLogin ? "Don't have an account? Register" : 'Already have an account? Login' }}
            </button>
        </form>
    </div>

    <!-- Password Change Prompt Dialog -->
    <div *ngIf="showPasswordChangePrompt" class="dialog-overlay">
        <div class="dialog-paper">
            <h2 class="dialog-title">Change Password Recommended</h2>
            <div class="dialog-content">
                <p class="dialog-content-text">
                    Your account was temporarily locked due to multiple failed login attempts.
                    For security reasons, we recommend changing your password. Would you like to change it now?
                </p>
            </div>
            <div class="dialog-actions">
                <button class="dialog-button" (click)="handlePasswordChangeNo()">No, Thanks</button>
                <button class="dialog-button primary" (click)="handlePasswordChangeYes()">Yes, Change Password</button>
            </div>
        </div>
    </div>
</div>
